# Generated by Django 4.0.3 on 2022-04-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_password2_signupmodel_confirmpassword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
