# Generated by Django 4.0.3 on 2022-04-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mothers_name', models.CharField(max_length=30)),
                ('fathers_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
            ],
        ),
    ]
