# Generated by Django 4.0.3 on 2022-04-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_registrationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='dob',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='email_id',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='pincode',
            field=models.TextField(max_length=5),
        ),
    ]
