# Generated by Django 4.0.3 on 2022-04-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_registrationmodel_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
