# Generated by Django 4.0.3 on 2022-04-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_registrationmodel_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationmodel',
            name='pin',
        ),
    ]
