# Generated by Django 4.0.3 on 2022-04-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_applymodel_delete_registrationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyModel',
        ),
    ]
